name: Feature Request
description: "For feature requests. Please search for existing issues first. Also see CONTRIBUTING."
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
     attributes:
      value: |
        Thanks for taking the time to fill out feature request!
  - type: textarea
    id: feature
    attributes:
      label: Describe your feature
      description: What would you like go-easy-instrumentation to be able to do? What new inputs would this require? What should the output look like?
      placeholder: What feature do you want?
      value: I would like to ....
    validations:
      required: true
